#!/bin/sh
set -e

do_systemd() {
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null ||:
    fi

    # monit
    systemctl unmask monit ||:
    systemctl preset monit ||:
    systemctl enable monit ||:

    if [ -d /run/systemd/system ]; then
        systemctl restart monit ||:
    fi
}

# In Yocto, monit looks at the /etc/monit.d/ directory
# instead of /etc/monit/conf.d/, so let's add the other directory to as well (for normalization)
if [ -f /etc/monitrc ]; then
    if ! grep -q "include /etc/monit/conf.d/\*" /etc/monitrc; then
        echo "Adding /etc/monit/conf.d/ to the monit config (/etc/monitrc)" >&2
        echo 'include /etc/monit/conf.d/*.conf' >> /etc/monitrc
    fi
fi

do_initd() {
    if command -V chkconfig >/dev/null 2>&1; then
        chkconfig --add monit ||:
    fi
    service monit restart ||:
}

if command -V systemctl >/dev/null 2>&1; then
    do_systemd
else
    do_initd
fi
