#!/bin/sh
set -e

do_systemd() {
    # monit
    systemctl disable monit ||:
    if [ -d /run/systemd/system ]; then
        systemctl stop monit ||:
    fi
}

do_initd() {
    service monit stop ||:
}

if command -V systemctl >/dev/null 2>&1; then
    do_systemd
else
    do_initd
fi
