#!/bin/sh
set -e

do_systemd() {
    # monit
    systemctl disable monit ||:
    if [ -d /run/systemd/system ]; then
        systemctl stop monit ||:
    fi
}

do_initd() {
    service monit stop ||:
}

remove_or_purge() {
    rm -f /etc/monit/conf.d/tedge-monitoring-extended.conf
    rm -f /usr/share/tedge-monit-setup/tedge-monitoring-legacy.conf

    if command -V systemctl >/dev/null 2>&1; then
        do_systemd
    else
        do_initd
    fi
}

action="$1"
case "$action" in
  "0" | "remove")
    remove_or_purge
    ;;
  "1" | "upgrade")
    # Do nothing on upgrade
    ;;
  "purge")
    remove_or_purge
    ;;
  *)
    remove_or_purge
    ;;
esac
